const SOURCE_MAP = {
  SPACE: 'space',
  // Editor
  EDT_FG: 'editor_foreground',
  EDT_BG: 'editor_background',
  // Sources
  SOURCE_JS: 'source_js',
  // Keywords
  KEY_CTRL_MOD_JS: 'keyword_control_module_js',
  KEY_CTRL_FLOW_JS: 'keyword_control_flow_js',
  KEY_OP_ACCESS_JS: 'keyword_operator_accessor_js',
  KEY_OP_LOGIC_JS: 'keyword_operator_logical_js',
  KEY_OP_ASSIGN_JS: 'keyword_operator_assignment_js',
  // Variables
  VAR_OTHER_RW_JS: 'variable_other_readwrite_js',
  VAR_OTHER_PROP_JS: 'variable_other_property_js',
  VAR_LANG_THIS_JS: 'variable_language_this_js',
  // Constants
  CONST_OTHER_OBJ_KEY_JS: 'constant_other_object_key_js',
  CONST_NUM_JS: 'constant_numeric_js',
  CONST_LANG_UNDEF_JS: 'constant_language_undefined_js',
  // Strings
  STR_QUO_MOD_JS: 'string_quoted_module_js',
  STR_QUO_SINGLE_JS: 'string_quoted_single_js',
  STR_QUO_DOUBLE_JS: 'string_quoted_double_js',
  STR_UNQUO_JS: 'string_unquoted_js',
  // Punctuation
  PUNC_DEF_STR_BEGIN_JS: 'punctuations_definition_string_begin_js',
  PUNC_TERM_STMT_JS: 'punctuation_terminator_statement_js',
  PUNC_SEC_CLS_BEGIN_JS: 'punctuation_section_class_begin_js',
  PUNC_DEF_TAG_JSX: 'puncutation_definition_tag_jsx',
  PUNC_DEF_PARAM_END_JS: 'puncutation_definition_parameters_end_js',
  PUNC_DEF_STR_BEGIN_JS: 'punctuation_definition_string_begin_js',
  PUNC_DEF_STR_END_JS: 'punctuation_definition_string_end_js',
  PUNC_SEP_KV_JS: 'punctuation_separator_key-value_js',
  PUNC_DEF_PARAM_BEGIN_JS: 'punctuation_definition_parameters_begin_js',
  PUNC_DEF_TAG_JS: 'punctuation_definition_tag_js',
  PUNC_SEC_CLS_END_JS: 'punctuation_section_class_end_js',
  PUNC_DEF_TAG_JSX: 'punctuation_definition_tag_jsx',
  PUNC_DEF_STR_BEGIN_JS: 'punctuation_definition_string_begin_jsx',
  PUNC_SEC_EMB_BEGIN_JSX: 'punctuation_section_embedded_begin_jsx',
  PUNC_SEC_EMB_END_JSX: 'punctuation_section_embedded_end_jsx',
  // Meta
  META_CLS_BODY_JS: 'meta_class_body_js',
  META_DEL_COMMA_JS: ' meta_delimiter_comma_js',
  META_FUNC_METH_JS: 'meta_function_method_js',
  META_CLS_JS: 'meta_class_js',
  META_BRACE_CURLY_JS: 'meta_brace_curly_js',
  META_FUNCCALL_WARG_JS: 'meta_function-call_with-arguments_js',
  META_METHCALL_WARG_JS: 'meta_method-call_with-arguments_js',
  META_FUNC_ARROW_JS: 'meta_function_arrow_js',
  META_FUNC_PARAM_JS: 'meta_function_parameters_js',
  META_PROP_OBJ_JS: 'meta_property_object_js',
  META_CLS_EXTD_JS: 'meta_class_extends_js',
  META_BRACE_ROUND_JS: 'meta_brace_round_js',
  META_BRACE_CURLY_LITOBJ_JS: 'meta_brace_curly_litobj_js',
  META_TAG_JS: 'meta_tag_js',
  META_TAG_JSX: 'meta_tag_jsx',
  META_EMB_EXPR_JS: 'meta_embedded_expression_js',
  // Storage
  STRG_TYPE_CLS_JS: 'storage_type_class_js',
  STRG_TYPE_EXTD_JS: 'storage_type_extends_js',
  STRG_TYPE_FUNC_ARROW_JS: 'storage_type_function_arrow_js',
  // Entity
  ENT_NAME_CLS_JS: 'entity_name_class_js',
  ENT_NAME_FUNC_METH_JS: 'entity_name_function_method_js',
  ENT_NAME_FUNC_JS: 'entity_name_function_js',
  ENT_NAME_TAG_OPEN_JSX: 'entity_name_tag_open_jsx',
  ENT_NAME_TAG_CLOSE_JSX: 'entity_name_tag_close_jsx',
  ENT_OTHER_ATTRNAME_JSX: 'entity_other_attribute-name_jsx',
  // Support
  SUPP_CLS_COMP_OPEN_JSX: 'support_class_component_open_jsx',
  // JSX
  JSXATTR: 'JSXAttrs',
  JSXNESTED: 'JSXNested',
  JSXSTARTTAGEND: 'JSXStartTagEnd',
  JSXENDTAGSTART: 'JSXEndTagStart',
};

export { SOURCE_MAP };